# Generated by Django 3.2.9 on 2021-11-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+7', max_length=11, verbose_name='Телефон'),
        ),
    ]
