# Generated by Django 3.2.9 on 2021-11-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
